# Question 4

In [1]:
# imports and setup

import scipy as sc
import numpy as np

import pandas as pd
import statsmodels.formula.api as sm
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

from IPython.display import Video

import matplotlib.pyplot as plt
%matplotlib inline  
plt.rcParams['figure.figsize'] = (10, 6)

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

In [5]:
ad = pd.read_csv('../DataMadness/DataSets/ad.csv')
grp = ad.groupby('brand')[['funny', 'show_product_quickly', 'patriotic', 'celebrity', 'danger', 'animals', 'use_sex']]
tmp = pd.DataFrame(grp.sum())
size = grp.size()
for index, row in tmp.iterrows():
    tmp.loc[index] = row.divide(size.loc[index])
tmp

,funny,show_product_quickly,patriotic,celebrity,danger,animals,use_sex
brand,,,,,,,
Bud Light,0.842105,0.894737,0.105263,0.368421,0.368421,0.421053,0.263158
Budweiser,0.117647,0.705882,0.647059,0.117647,0.235294,0.647059,0.176471
Coca-Cola,0.380952,0.714286,0.238095,0.285714,0.285714,0.571429,0.047619
Doritos,0.960000,0.880000,0.040000,0.160000,0.440000,0.400000,0.240000
Hynudai,0.578947,0.473684,0.157895,0.315789,0.315789,0.368421,0.157895
Kia,0.500000,0.200000,0.200000,0.600000,0.400000,0.400000,0.300000
Pepsi,0.720000,0.600000,0.120000,0.640000,0.240000,0.120000,0.440000
Toyota,0.545455,0.818182,0.181818,0.181818,0.363636,0.272727,0.090909